# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionRawDataModel',
            fields=[
                ('id', models.CharField(db_column='pk', max_length=65, primary_key=True, serialize=False)),
                ('security_type', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=6)),
                ('symbol', models.CharField(max_length=6)),
                ('option_symbol', models.CharField(max_length=6)),
                ('option_maturity', models.CharField(max_length=6)),
                ('underlying_maturity', models.CharField(max_length=6)),
                ('last_trading_day', models.DateField()),
                ('bizdt', models.DateField()),
                ('undprice', models.FloatField(blank=True, null=True)),
                ('putcall', models.IntegerField(blank=True, null=True)),
                ('strkpx', models.FloatField(blank=True, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('settleprice', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('oi', models.IntegerField(blank=True, null=True)),
                ('yte', models.FloatField(blank=True, null=True)),
                ('moneyness', models.FloatField(blank=True, null=True)),
                ('divyield', models.FloatField(blank=True, null=True)),
                ('rfr', models.FloatField(blank=True, null=True)),
                ('rawiv', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('tv', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'options_rawdata',
            },
        ),
    ]
